server:
    port: 8080

api:
  openai:
    key: ${OPENAI_API_KEY}
    model: ${OPENAI_MODEL:gpt-4o}
    embeddingModel: ${OPENAI_EMBEDDING_MODEL:text-embedding-3-large}
  brave:
    key: ${BRAVE_API_KEY}

agent:
  max-iterations: 5
  scrape-concurrency: 5
  similarity-threshold: 0.95
